---
title: "README"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  html_document:
    keep_md: true
---

## Symmetry Sorting Project

Behavioral studies associated with the symmetry sorting project. 

Last updated `r Sys.time()`.

## Contents

- [analysis-planning.Rmd](analysis-planning.Rmd), ioslides presentation for meeting with AMN and AC. [HTML](https://rawgit.com/gilmore-lab/symmetry-sorting/master/analysis-planning.html)
- [imgs/](imgs), Image files produced in analysis.
- [notes/](notes), text/Markdown formatted project notes.
- [pubs/](pubs), publications associated with the project
- [analysis/](analysis/), R code and data
    - [analysis/data/](analysis/data/)
        - [analysis/data/xlsx/](analysis/data/xlsx/), Excel format spreadsheets used to record data
        - *.csv, comma-delimited text files used for analysis in R
    - *.R, R functions
- [vedak-etal-2015/](vedak-etal-2015), files from earlier VSS analysis and presentation.

## R Session Info

```{r session-info}
sessionInfo()
```

## Sorting task description

The Gilmore Research lab at Penn State asked student volunteers to look at a number of different types of patterns and share how they organized them into groups as they saw fit. The 5 pattern groups used each consisted of 20 individual patterns tied together only by having a specific type of symmetry or combination of symmetries. The four primary symmetry types, each included by itself or in combination with one or more of the other types in these groups, include reflection, translation, rotation, and glide reflection. These represent the modifications an initial pattern underwent in order to create the final designs. 

A reflection is a copy of the initial pattern that is like its mirror image, and would return to the initial pattern if simply flipped over an axis. A translation is a copy that would return to the original image if simply slid in one direction to line up with it. A rotation is a copy that would return to the original image if moved while anchored to a specific rotational point. A glide reflection is a reflection over two, typically perpendicular, axes so that flipping the copy over either axis would make it a direct reflection of the initial image that would return to it if flipped over the other axis.

There are 17 [wallpaper groups](https://en.wikipedia.org/wiki/Wallpaper_group) that result from the combination of these symmetry types. The 5 wallpaper groups used in the present study were: P1, P3M1, P31M, P6, P6M.

Participants were shown one group at a time, and instructed to divide it into as many subgroups as they saw. Their explanations for the groupings they created will help us to understand some of the ways in which people perceive and distinguish between different types of symmetry.
