---
title: "wallpaper-image-metrics-analysis"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  ioslides_presentation:
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(ggplot2)
require(dplyr)
require(png)

source('analysis/image.dot.prod.R')
source('analysis/ssim.R')
source('analysis/compute.image.metric.R')
source('analysis/norm.vect.R')
source('analysis/fit.plot.mds.R')
source('analysis/fit.clust.R')
source('analysis/plot.clust.R')
source('analysis/plot.mds.R')

wp.groups <- c('P1', 'P3M1', 'P31M', 'P6', 'P6M')
group <- wp.groups[1]
image.metric = 'ssim' # 'image.dot.prod'
cluster.method = 'mds' # 'hclust'
dim = 3
```

## `r image.metric` on `r group` via `r cluster.method`

<div class="centered">
```{r, echo=FALSE, warning=FALSE}
stat.val <- compute.image.metric(group = group, sf = 1, duplicates = TRUE, frame=FALSE,  FUN=image.metric, analysis.dir = 'analysis/')

d <- dist(1 - stat.val)
fit <- fit.clust(d, cluster.method, dim=2)
plot.clust(fit, cluster.method)
```
</div>