---
title: "dotprod-mds-analysis"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  ioslides_presentation:
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(ggplot2)
require(dplyr)
require(png)
```

## Computing Image-wise Dot Product

- $Dot(A,B)=\frac{A \cdot B}{|A||B|}$

```{r ssim-P1, echo=FALSE}
source('analysis/image.dot.prod.R')
source('analysis/compute.image.metric.R')
source('analysis/norm.vect.R')
source('analysis/fit.plot.mds.R')

wp.groups <- c('P1', 'P3M1', 'P31M', 'P6', 'P6M')
group <- wp.groups[1]
```

## Multidimensional Scaling of A•B on `r group`

<div class="centered">
```{r, echo=FALSE, warning=FALSE}
dotprod.val <- compute.image.metric(group = group, sf = 1, duplicates = TRUE, frame=FALSE,  FUN=image.dot.prod, analysis.dir = 'analysis/')
d <- dist(1 - dotprod.val)
fit.plot.mds(group=group, d)

group <- wp.groups[2]
```
</div>

## Multidimensional Scaling of A•B on `r group`

<div class="centered">
```{r, echo=FALSE, warning=FALSE}
dotprod.val <- compute.image.metric(group = group, sf = 1, duplicates = TRUE, frame=FALSE,  FUN=image.dot.prod, analysis.dir = 'analysis/')
d <- dist(1 - dotprod.val)
fit.plot.mds(group=group, d)

group <- wp.groups[3]
```
</div>

## Multidimensional Scaling of A•B on `r group`

<div class="centered">
```{r, echo=FALSE, warning=FALSE}
dotprod.val <- compute.image.metric(group = group, sf = 1, duplicates = TRUE, frame=FALSE,  FUN=image.dot.prod, analysis.dir = 'analysis/')
d <- dist(1 - dotprod.val)
fit.plot.mds(group=group, d)

group <- wp.groups[4]
```
</div>

## Multidimensional Scaling of A•B on `r group`

<div class="centered">
```{r, echo=FALSE, warning=FALSE}
dotprod.val <- compute.image.metric(group = group, sf = 1, duplicates = TRUE, frame=FALSE,  FUN=image.dot.prod, analysis.dir = 'analysis/')
d <- dist(1 - dotprod.val)
fit.plot.mds(group=group, d)

group <- wp.groups[5]
```
</div>

## Multidimensional Scaling of A•B on `r group`

<div class="centered">
```{r, echo=FALSE, warning=FALSE}
dotprod.val <- compute.image.metric(group = group, sf = 1, duplicates = TRUE, frame=FALSE,  FUN=image.dot.prod, analysis.dir = 'analysis/')
d <- dist(1 - dotprod.val)
fit.plot.mds(group=group, d)
```
</div>
